import type { Lang } from "./content";

export const biography: Record<Lang, { title: string; read: string; back: string; paragraphs: string[] }> = {
  uk: {
    title: "Біографія",
    read: "Читати повну біографію",
    back: "Повернутися на головну",
    paragraphs: [
      "Сімона Вілар та Наталія Образцова — літературні псевдоніми відомої української письменниці Наталії Гавриленко.",
      "Наталія написала 29 любовно-історичних романів.",
      "У 2011 році очолила ТОП-10 найуспішніших письменників України, а в 2012 стала лауреатом літературної премії «Золоті письменники України».",
      "Сімона Вілар народилася в Харкові, на сході України. З дитинства вона була захоплена читанням і мріяла стати письменницею. Проте творчий шлях був непростим.",
      "На початку свого творчого шляху Сімона Вілар випробовувала свої перші твори на чоловікові. Вона розповідала йому свої історії, а його реакція та підтримка були для неї натхненням. Однак довго вона сумнівалася і коливалася, перед тим як вирішитися піти до видавництва. Її перші редактори були готові взяти її з вулиці, дати їй шанс, і вони не пошкодували про свій вибір. Коли вони прочитали її першу книгу, вони були вражені й швидко запропонували її твір великому видавництву.",
      "Проте наприкінці 90-х років сталися дві трагічні події — загинув чоловік Наталії, залишивши її з трирічною донькою, і водночас було розірвано перший видавничий контракт.",
      "Наступні декілька років життя були максимально важкими. Щоб підтримати себе і дитину, колись успішна авторка була готова на все: ремонтувала квартири, працювала в кіоску, навіть була вахтеркою в гуртожитку цілодобово. На написання книг не залишалося часу. Здавалося, що перший успіх був просто удачею і більше не повториться.",
      "Коли здавалося, що ніхто не вірить в її талант, одне харківське видавництво дало шанс. Маловідоме тоді видавництво, яке займалося бухгалтерською літературою, вирішило надрукувати її книги. Тоді, у 2000 році, Сімона придбала свій перший комп'ютер і продовжила творчий шлях. Це був переломний момент в її житті, коли вона зрозуміла, що здатна здійснити свою мрію.",
      "Творча праця завжди виснажує, і Сімона Вілар намагається відновлюватися після неї тим, що любить і радує. Вона читає книги, дивиться фільми, спілкується з друзями, слухає музику. Але головне для неї — це подорожі. Сімона обожнює їздити на велосипеді, лижах, ходити в гори, і подорожі стали частиною творчого процесу. Вона старається відвідувати місця, про які потім пише у своїх романах, щоб краще зануритися в атмосферу і створити живі та реалістичні світи.",
      "Для Сімони Вілар письменництво — це не просто професія, а справжнє покликання. Вона завжди відчувала, що доля призначила їй писати та створювати дивовижні світи для своїх читачів. Її романи не тільки приносять задоволення, але й запалюють у серцях читачів вогонь пристрасті до історії та книг.",
    ],
  },
  ru: {
    title: "Биография",
    read: "Читать полную биографию",
    back: "Вернуться на главную",
    paragraphs: [
      "Симона Вилар и Наталья Образцова — литературные псевдонимы известной украинской писательницы Наталии Гавриленко.",
      "Наталья написала 29 любовно-исторических романов.",
      "В 2011 году возглавила ТОП-10 самых успешных писателей Украины, а в 2012 стала лауреатом литературной награды «Золотые писатели Украины».",
      "Симона Вилар родилась в Харькове, на востоке Украины. С детства она была увлечена чтением и мечтала стать писательницей. Но творческая дорога была непростой.",
      "В начале своего творческого пути Симона Вилар испытывала свои первые произведения на муже. Она рассказывала ему свои истории, и его реакция и поддержка были для неё вдохновляющими. Однако долго она сомневалась и колебалась, прежде чем решиться пойти в издательство. Её первые редакторы были готовы взять её с улицы, дать ей шанс, и они не пожалели о своем выборе. Когда они прочитали её первую книгу, они были впечатлены и быстро предложили её произведение крупному издательству.",
      "Однако в конце 90-х годов произошло два трагических события — погиб муж Наталии, оставив её с трёхлетней дочерью, и в то же время был разорван первый издательский контракт.",
      "Следующие несколько лет жизни были максимально тяжёлыми. Чтобы поддержать себя и дочь, когда-то успешный автор была готова на всё: делала ремонты в квартирах, работала в киоске, даже была вахтёром в общежитии сутки напролёт. На написание книг не было времени. Казалось, что первый успех был просто удачей и больше не повторится.",
      "Когда казалось, что никто не верит в её талант, одно харьковское издательство дало шанс. Малоизвестное тогда издательство, занимающееся бухгалтерской литературой, решило напечатать её книги. Тогда, в 2000 году, Симона купила свой первый компьютер и продолжила творческий путь. Это был переломный момент в её жизни, когда она поняла, что способна сделать свою мечту реальностью.",
      "Творческий труд всегда выматывает, и Симона Вилар старается восстанавливаться после него тем, что любит и радует. Она читает книги, смотрит фильмы, общается с друзьями, слушает музыку. Но главное для неё — это путешествия. Симона обожает ездить на велосипеде, лыжах, ходить в горы, и путешествия для неё стали частью творческого процесса. Она старается посетить места, о которых потом пишет в своих романах, чтобы лучше погрузиться в атмосферу и создать живые и реалистичные миры.",
      "Для Симоны Вилар писательство — это не просто профессия, а истинное призвание. Она всегда чувствовала, что судьба предназначила ей писать и создавать удивительные миры для своих читателей. Её романы не только приносят удовольствие, но и зажигают в сердцах читателей огонь страсти к истории и книгам.",
    ],
  },
  en: {
    title: "Biography",
    read: "Read full biography",
    back: "Back to home",
    paragraphs: [
      "Simona Vilar and Natalia Obraztsova are literary pen names of the well-known Ukrainian writer Natalia Gavrilenko.",
      "Natalia has written 29 historical romance novels.",
      "In 2011 she topped the list of Ukraine's ten most successful writers, and in 2012 she received the literary award \"Golden Writers of Ukraine.\"",
      "Simona Vilar was born in Kharkiv, in eastern Ukraine. From childhood she loved reading and dreamed of becoming a writer. But her creative path was not an easy one.",
      "At the start of her career, Simona Vilar tested her first stories on her husband. She would tell him her stories, and his reaction and support inspired her. Even so, she hesitated and doubted for a long time before deciding to approach a publisher. Her first editors were willing to take a chance on someone off the street, and they never regretted it. When they read her first book, they were impressed and quickly recommended her work to a major publishing house.",
      "But in the late 1990s two tragic events occurred: Natalia's husband died, leaving her with a three-year-old daughter, and at the same time her first publishing contract fell through.",
      "The following years were extremely difficult. To support herself and her daughter, the once-successful author was ready to do anything: she renovated apartments, worked at a kiosk, and even worked around the clock as a caretaker in a student dormitory. There was no time left for writing. It seemed that her early success had simply been luck, and that it would not come again.",
      "Just when it seemed that no one believed in her talent, a publishing house in Kharkiv gave her a chance. A little-known publisher that mainly produced accounting literature decided to print her books. That year, 2000, Simona bought her first computer and continued on her creative path. It was a turning point in her life, the moment she realized she was capable of making her dream a reality.",
      "Creative work is always exhausting, and Simona Vilar tries to recover from it by doing what she loves and what brings her joy. She reads books, watches films, spends time with friends, and listens to music. But travel matters most to her. Simona loves cycling, skiing, and hiking in the mountains, and travel has become part of her creative process. She tries to visit the places she later writes about in her novels, so as to better absorb their atmosphere and create living, realistic worlds.",
      "For Simona Vilar, writing is not simply a profession but a true calling. She has always felt that fate meant for her to write and to create wondrous worlds for her readers. Her novels not only bring pleasure but also kindle in readers' hearts a passion for history and books.",
    ],
  },
};
